#!/bin/bash
#SBATCH --job-name=sd-tuning   # Kurzname des Jobs
#SBATCH --nodes=1                 # Anzahl benötigter Knoten
#SBATCH --ntasks=1                # Gesamtzahl der Tasks über alle Knoten hinweg
#SBATCH --partition=p0            # Verwendete Partition (z.B. p0, p1, p2 oder all)
#SBATCH --time=08:00:00           # Gesamtlimit für Laufzeit des Jobs (Format: HH:MM:SS)
#SBATCH --cpus-per-task=8         # Rechenkerne pro Task
#SBATCH --mem=24G                 # Gesamter Hauptspeicher pro Knoten
#SBATCH --gres=gpu:1              # Gesamtzahl GPUs pro Knoten
#SBATCH --qos=basic               # Quality-of-Service
#SBATCH --mail-type=ALL           # Art des Mailversands (gültige Werte z.B. ALL, BEGIN, END, FAIL oder REQUEUE)
#SBATCH --mail-user=kremlingph95027@th-nuernberg.de # Emailadresse für Statusmails

echo "=================================================================="
echo "Starting Batch Job at $(date)"
echo "Job submitted to partition ${SLURM_JOB_PARTITION} on ${SLURM_CLUSTER_NAME}"
echo "Job name: ${SLURM_JOB_NAME}, Job ID: ${SLURM_JOB_ID}"
echo "Requested ${SLURM_CPUS_ON_NODE} CPUs on compute node $(hostname)"
echo "Working directory: $(pwd)"
echo "=================================================================="

###################### Optional for Pythonnutzer*innen #######################
# Die folgenden Umgebungsvariablen stellen sicher, dass
# Modellgewichte von Huggingface und PIP Packages nicht unter 
# /home/$USER/.cache landen. 
CACHE_DIR=/nfs/scratch/students/$USER/.cache
export PIP_CACHE_DIR=$CACHE_DIR
export TRANSFORMERS_CACHE=$CACHE_DIR
export HF_HOME=$CACHE_DIR
mkdir -p "$CACHE_DIR"
########################################################

############### Starte eigenen Job hier ################
srun accelerate launch train_text_to_image_lora.py \
  --pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5 \
  --train_data_dir="data" \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=16 \
  --num_train_epochs=100 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="output" \
  --validation_prompt="a brown dog"
########################################################